### ISSUE TITLE
Nested A tags parsed improperly

### ISSUE THREAD

**Issue by nonara** [taoqf/node-html-parser#144]
## Synopsis

Given:
```html
<a href="#">link <a href="#">nested link</a> end</a>
```

This is invalid HTML, and it should be parsed as:

```
<A>
 |-- <TextNode text="link ">
<A>
 |-- <TextNode text="nested link">
<TextNode text=" end">
```

However, it's parsed as:

```
<A>
 |-- <TextNode text="link ">
 |-- <A>
      |-- <TextNode text="nested link">
 |-- <TextNode text=" end">
```

This is causing issues for the markdown converter.

## Spec

Spec dictates that an `A` tag cannot be a child of another `A`.

Upon encountering a nested A tag, the parser should consider the present tag terminated and begin a new one. Any further text that occurs after (ie. ` end`, should be considered a TextNode)

This behaviour can be demonstrated via: https://astexplorer.net

## Solution

I believe this should be easily solvable, without a performance impact. I will investigate this ASAP and submit a fix. I hope to get to it this weekend.

## Related

- https://github.com/crosstype/node-html-markdown/issues/25

**Comment by taoqf** [comment]
Fixed, and I do believe this would reduce the performance a bit. but it should not works incorrectly anyway. Thanks for your report. reopen this if issues are still there.

**Comment by nonara** [comment]
Thanks for the fast work! I think there will still be an issue, though.

```html
<a href="#"><b><a href="#">link</a></b></a>
```

My plan was to track the last A tag stack index in a var, and if you hit another, it would adjust the stack from the var idx point and update the var with the new tag

**Comment by nonara** [comment]
Fix submitted in #148

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/issues/211

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/issues/211

**Comment by taoqf** [comment]
It seems #148 caused more issues.

**Comment by taoqf** [comment]
@nonara Do you have time to take a look at these issues?

**Comment by nonara** [comment]
Hi @taoqf ! Good to hear from you. Hope all is well.

I will check on the behavior of other parsers. I think how we handle it matches, but if not, I'll give some thought to the right approach and we can discuss a way to correct it

**Comment by taoqf** [comment]
@nonara Thanks, really.

**Comment by nonara** [comment]
Resolved in #215

**Comment by Hurtak** [comment]
I think this issue is still present, I am getting these results on 7.0.1

```ts
      const content = `
        <p>
          <p>Some nested paragraph</p>
        </p>
      `;
      const parsed = parse(content);
      const nestedParagraphs = parsed.querySelectorAll('p p');
      console.log(nestedParagraphs); // []
      console.log(parsed.outerHTML); // <p></p><p>Some nested paragraph</p>
```
